name = "Create New Horizons"
author = "Erik Donath"
version = "1.0.5"
description = "Create New Horizons is a lightweight Create-focused modpack centered around factories, railways, and flying machines."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a33a80441c4e074a3f788ad9f1383b466d3d9868231d7d2efed1d415a2df121"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
