name = "Create New Horizons"
author = "Erik Donath"
version = "0.0.3"
description = "Create New Horizons is a lightweight Create-focused modpack centered around factories, railways, and flying machines."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a5d3c194bbfd55108d3096bfd07062281a5a19fc60c39c3672782746eea55e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
