---
name: Release Modpack

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh Pack
        run: packwiz refresh

      - name: Export Modrinth Pack
        run: packwiz modrinth export

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: "*.mrpack"

          name: ${{ github.event.release.name }}
          version: ${{ github.ref_name }}

          version-type: release

          loaders: |
            neoforge

          game-versions: |
            1.21.1

          changelog: ${{ github.event.release.body }}